# Generated by Django 5.1 on 2024-11-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip', models.CharField(max_length=45)),
                ('original_url', models.TextField()),
                ('user_agent', models.TextField()),
                ('headers', models.JSONField()),
                ('fw_res', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('query', models.JSONField()),
                ('cookies', models.JSONField()),
            ],
            options={
                'db_table': 'http_request',
            },
        ),
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=100)),
                ('blacklist', models.BooleanField()),
            ],
            options={
                'db_table': 'ip_info',
            },
        ),
        migrations.CreateModel(
            name='TcpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_port', models.IntegerField()),
            ],
            options={
                'db_table': 'tcp_connection',
            },
        ),
    ]
