# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiguard.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'aiguard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import genericval_pb2 as genericval__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raiguard.proto\x12\x07\x61iguard\x1a\x10genericval.proto\"u\n\x12\x41iGuardHttpRequest\x12,\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x1c.aiguard.AiGuardCommonParams\x12\x31\n\x06params\x18\x02 \x01(\x0b\x32!.aiguard.AiGuardHttpRequestParams\"\xe6\x03\n\x18\x41iGuardHttpRequestParams\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t\x12\x37\n\nuser_agent\x18\x02 \x01(\x0b\x32\x1e.genericval.AppGuardGenericValH\x00\x88\x01\x01\x12?\n\x07headers\x18\x03 \x03(\x0b\x32..aiguard.AiGuardHttpRequestParams.HeadersEntry\x12\x0e\n\x06method\x18\x04 \x01(\t\x12;\n\x05query\x18\x05 \x03(\x0b\x32,.aiguard.AiGuardHttpRequestParams.QueryEntry\x12\x34\n\x07\x63ookies\x18\x06 \x01(\x0b\x32\x1e.genericval.AppGuardGenericValH\x01\x88\x01\x01\x1aN\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.genericval.AppGuardGenericVal:\x02\x38\x01\x1aL\n\nQueryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.genericval.AppGuardGenericVal:\x02\x38\x01\x42\r\n\x0b_user_agentB\n\n\x08_cookies\"\xe1\x01\n\x13\x41iGuardCommonParams\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x16\n\tsource_ip\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bsource_port\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x14\n\x07\x63ountry\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x03\x61sn\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x10\n\x03org\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x11\n\tblacklist\x18\x07 \x01(\rB\x0c\n\n_source_ipB\x0e\n\x0c_source_portB\n\n\x08_countryB\x06\n\x04_asnB\x06\n\x04_org\"6\n\x0f\x41iGuardResponse\x12\x12\n\nconfidence\x18\x01 \x01(\x01\x12\x0f\n\x07\x63olumns\x18\x02 \x03(\t2U\n\x07\x41iGuard\x12J\n\x11HandleHttpRequest\x12\x1b.aiguard.AiGuardHttpRequest\x1a\x18.aiguard.AiGuardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiguard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIGUARDHTTPREQUESTPARAMS_HEADERSENTRY']._loaded_options = None
  _globals['_AIGUARDHTTPREQUESTPARAMS_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_AIGUARDHTTPREQUESTPARAMS_QUERYENTRY']._loaded_options = None
  _globals['_AIGUARDHTTPREQUESTPARAMS_QUERYENTRY']._serialized_options = b'8\001'
  _globals['_AIGUARDHTTPREQUEST']._serialized_start=44
  _globals['_AIGUARDHTTPREQUEST']._serialized_end=161
  _globals['_AIGUARDHTTPREQUESTPARAMS']._serialized_start=164
  _globals['_AIGUARDHTTPREQUESTPARAMS']._serialized_end=650
  _globals['_AIGUARDHTTPREQUESTPARAMS_HEADERSENTRY']._serialized_start=467
  _globals['_AIGUARDHTTPREQUESTPARAMS_HEADERSENTRY']._serialized_end=545
  _globals['_AIGUARDHTTPREQUESTPARAMS_QUERYENTRY']._serialized_start=547
  _globals['_AIGUARDHTTPREQUESTPARAMS_QUERYENTRY']._serialized_end=623
  _globals['_AIGUARDCOMMONPARAMS']._serialized_start=653
  _globals['_AIGUARDCOMMONPARAMS']._serialized_end=878
  _globals['_AIGUARDRESPONSE']._serialized_start=880
  _globals['_AIGUARDRESPONSE']._serialized_end=934
  _globals['_AIGUARD']._serialized_start=936
  _globals['_AIGUARD']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
